### ISSUE TITLE
each metric as its own row

### ISSUE THREAD

**Issue by dailow** [lephisto/tesla-apiscraper#12]
Maybe I'm not familiar with influxdb, but it seems that each metric is captured in its own row and I'm not sure if that is the desired behavior?  For example the query below would only return the charge_limit_soc and not the other values in charge_state.

`SELECT * FROM charge_state WHERE charge_limit_soc = 80`

**Comment by lephisto** [comment]
This is known and will be changed in some days. In most cases it does not matter, but i aggree that it's not too smart..

**Comment by dailow** [comment]
Thanks, let me know if I can help.  I was thinking of just removing the metric when inserting the data and re-doing the dashboards.

**Comment by lephisto** [comment]
Dashboards are adjusted already..

**Comment by lephisto** [comment]
Refactored in 5ba49bfe37a2c33b21fdb73618a8e045e9fdb7b0 currently in v2019.4 development branch. Should work downwards compatible.

**Comment by lephisto** [comment]
Confirmed working. closing down here
