### ISSUE TITLE
add support for farenheit

### ISSUE THREAD

**Issue by ochaine** [lephisto/tesla-apiscraper#2]
similar to miles and km, can we have variables for degrees F vs. C?

**Comment by lephisto** [comment]
Yes, will be added until next Weekend. New Dashboards are coming up..

**Comment by lephisto** [comment]
Regarding the Temperature C to F:

You can do this by yourself:

Add Template Variable "tempfactor", type "custom", Value: "* 9 / 5 + 32" and add math($tempfactor) where you need it and change the Unit in the Panel Properties.

I will probably include this in v2019.4 release, which is on the way.

**Comment by lephisto** [comment]
Support for this is in the current master, with some limitations. The thresholds for Gauges can't be set through template variables/formulas. You have to adjust them manually according your needs everytime you imported the Dashboards..

**Comment by lephisto** [comment]
This is implemented now.
