### ISSUE TITLE
Idea: Enhance config with scheduled wakeup times

### ISSUE THREAD

**Issue by markusdd** [lephisto/tesla-apiscraper#23]
Hi, thanks for this amazing little tool.

Especially in the mornings and after work it would be amazing if the car would be woken up automatically so the app is directly able to connect, e.g. for starting the pre-heating or cooling.

I imagine something like cron, where you can say: Wake up the car Mo-Fr at 6 am, so that at 6:30 one can easily start the pre-heating.

**Comment by lephisto** [comment]
A Schedule is something we can think of. The other option would be to issue the command through the python daemon, which would violate a design principle, though.. We will discuss it.

**Comment by lephisto** [comment]
Implemented in e13596e06d0b2e8236d6a43f8db3ab8b6459c408
