### ISSUE TITLE
NameError: name 'a_start_disabled' is not defined

### ISSUE THREAD

**Issue by GekoCH** [lephisto/tesla-apiscraper#25]
error in apiscraper.py.
The value 'a_start_disabled' is not defined and therefore this error.
This part of the code has been added 7days ago...

**Comment by lephisto** [comment]
Can't relate to that: 

https://github.com/lephisto/tesla-apiscraper/blob/master/config.py.dist#L12

**Comment by GekoCH** [comment]
yes, just realized that I have to udpate the config file as well, thx
