### ISSUE TITLE
Not an issue but a question..

### ISSUE THREAD

**Issue by scsinutz** [lephisto/tesla-apiscraper#26]
` If the car is awake, the API keeps it awake, as long as requests occur`

Need some clarification. Does the tesla-apiscraper prevent the car from going into sleep mode? 

It seems that my car (Model 3) is constantly awake when I run the api-scraper

**Comment by lephisto** [comment]
I should better have written "keep it awake as long as value changes occur. Sometimes Autosleeping works, sometimes not. This is why I made that little Android app, that disables scraping when you leave the car and it's not charging (and if you plugged it in it scrapes in 16 second intervals until charging ends), and re-enables scraping when you get in proximity to the car.

**Comment by picard001** [comment]
I have further questions regarding this.  I leave mine plugged in all night but it appears some variables change just slightly which cause it to continue to scrape the car.  This is a Model 3:

> 2019-04-05 22:39:20 INFO     >> Request vehicle data
> 2019-04-05 22:39:21 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 2, new value: 1
> 2019-04-05 22:39:21 INFO     Asleep since: 0 Sleeping for 8 seconds..
> 2019-04-05 22:39:29 INFO     Car State: online Poll Interval: 8
> 2019-04-05 22:39:29 INFO     >> Request vehicle data
> 2019-04-05 22:39:30 INFO     Value Change, SG: charge_state: Logging...battery_range: old value: 262.08, new value: 261.73
> 2019-04-05 22:39:30 INFO     Value Change, SG: charge_state: Logging...charge_energy_added: old value: 1.32, new value: 1.24
> 2019-04-05 22:39:30 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 1, new value: 2
> 2019-04-05 22:39:30 INFO     Value Change, SG: charge_state: Logging...est_battery_range: old value: 247.45, new value: 247.12
> 2019-04-05 22:39:30 INFO     Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 262.08, new value: 261.73
> 2019-04-05 22:39:30 INFO     Asleep since: 0 Sleeping for 4 seconds..
> 2019-04-05 22:39:34 INFO     Car State: online Poll Interval: 4
> 2019-04-05 22:39:34 INFO     >> Request vehicle data
> 2019-04-05 22:39:34 INFO     Asleep since: 0 Sleeping for 8 seconds..
> 2019-04-05 22:39:42 INFO     Car State: online Poll Interval: 8
> 2019-04-05 22:39:42 INFO     >> Request vehicle data
> 2019-04-05 22:39:43 INFO     Value Change, SG: charge_state: Logging...battery_range: old value: 261.73, new value: 262.08
> 2019-04-05 22:39:43 INFO     Value Change, SG: charge_state: Logging...charge_energy_added: old value: 1.24, new value: 1.32
> 2019-04-05 22:39:43 INFO     Value Change, SG: charge_state: Logging...est_battery_range: old value: 247.12, new value: 247.45
> 2019-04-05 22:39:43 INFO     Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 261.73, new value: 262.08
> 2019-04-05 22:39:43 INFO     Asleep since: 0 Sleeping for 4 seconds..
> 2019-04-05 22:39:47 INFO     Car State: online Poll Interval: 4
> 2019-04-05 22:39:47 INFO     >> Request vehicle data
> 2019-04-05 22:39:48 INFO     Value Change, SG: charge_state: Logging...battery_range: old value: 262.08, new value: 261.73
> 2019-04-05 22:39:48 INFO     Value Change, SG: charge_state: Logging...charge_energy_added: old value: 1.32, new value: 1.24
> 2019-04-05 22:39:48 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 2, new value: 1
> 2019-04-05 22:39:48 INFO     Value Change, SG: charge_state: Logging...est_battery_range: old value: 247.45, new value: 247.12
> 2019-04-05 22:39:48 INFO     Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 262.08, new value: 261.73
> 2019-04-05 22:39:48 INFO     Asleep since: 0 Sleeping for 2 seconds..
> 2019-04-05 22:39:50 INFO     Car State: online Poll Interval: 2
> 2019-04-05 22:39:50 INFO     >> Request vehicle data
> 2019-04-05 22:39:50 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 1, new value: 2
> 2019-04-05 22:39:50 INFO     Asleep since: 0 Sleeping for 1 seconds..
> 2019-04-05 22:39:51 INFO     Car State: online Poll Interval: 1
> 2019-04-05 22:39:51 INFO     >> Request vehicle data
> 2019-04-05 22:39:52 INFO     Asleep since: 0 Sleeping for 2 seconds..
> 2019-04-05 22:39:54 INFO     Car State: online Poll Interval: 2
> 2019-04-05 22:39:54 INFO     >> Request vehicle data
> 2019-04-05 22:39:55 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 2, new value: 1
> 2019-04-05 22:39:55 INFO     Asleep since: 0 Sleeping for 1 seconds..
> 2019-04-05 22:39:56 INFO     Car State: online Poll Interval: 1
> 2019-04-05 22:39:56 INFO     >> Request vehicle data
> 2019-04-05 22:39:56 INFO     Value Change, SG: charge_state: Logging...battery_range: old value: 261.73, new value: 262.08
> 2019-04-05 22:39:56 INFO     Value Change, SG: charge_state: Logging...charge_energy_added: old value: 1.24, new value: 1.32
> 2019-04-05 22:39:56 INFO     Value Change, SG: charge_state: Logging...est_battery_range: old value: 247.12, new value: 247.45
> 2019-04-05 22:39:56 INFO     Value Change, SG: charge_state: Logging...ideal_battery_range: old value: 261.73, new value: 262.08
> 2019-04-05 22:39:56 INFO     Asleep since: 0 Sleeping for 1 seconds..
> 2019-04-05 22:39:57 INFO     Car State: online Poll Interval: 1
> 2019-04-05 22:39:57 INFO     >> Request vehicle data
> 2019-04-05 22:39:58 INFO     Value Change, SG: charge_state: Logging...charger_voltage: old value: 1, new value: 2
> 2019-04-05 22:39:58 INFO     Asleep since: 0 Sleeping for 1 seconds..
> 2019-04-05 22:39:59 INFO     Car State: online Poll Interval: 1
> 2019-04-05 22:39:59 INFO     >> Request vehicle data
> 2019-04-05 22:40:00 INFO     Asleep since: 0 Sleeping for 2 seconds..
> 2019-04-05 22:40:02 INFO     Car State: online Poll Interval: 2
> 2019-04-05 22:40:02 INFO     >> Request vehicle data
> 2019-04-05 22:40:03 INFO     Asleep since: 0 Sleeping for 4 seconds..

Would it be possible to add further detection to catch these small/insignifigant changes and ignore them, allowing the vehicle to go into a "deep" sleep?
