### ISSUE TITLE
Q: What does the charging_state toggle mean on the Charging Dashboard?

### ISSUE THREAD

**Issue by jat255** [lephisto/tesla-apiscraper#29]
Thanks for this project! I just got it set up on my server, and I'm really liking it so far. I was wondering, what the output of the `charging_state` toggle is on the Charging dashboard:

![image](https://user-images.githubusercontent.com/1278301/55130734-4e735600-50f2-11e9-8722-ee43bff3c8fc.png)

I see that it adds a few vertical dashed lines, that I'm guessing are supposed to be changes in charging status? I have two of them on my (admittedly short) graph history so far, even though the car has been continuously charging the whole time.

**Comment by lephisto** [comment]
It reads event annotations from the Database (like Charge Start, Charge end etc).
