### ISSUE TITLE
Battery health/projected max range

### ISSUE THREAD

**Issue by CoMPaTech** [lephisto/tesla-apiscraper#34]
Nice work on this, just switched over from teslams and a lot of own custom code. One of the things I took from another owner is displaying battery health using the cars own values. (Basically ideal range vs battery level graphed out).

Not sure what would be the best way to share this panel added the rough JSON excerpt here (https://gist.github.com/CoMPaTech/32706c8cc9a7b31701a6267ac146b1c8) do note the entries to be changed.

**Comment by lephisto** [comment]
Could you use the Share for export function so I could test this.

**Comment by CoMPaTech** [comment]
The full dashboard https://gist.github.com/CoMPaTech/6c508dd9e7c386a19a9612b183e11f14 though you need to modify `CARNAME` probably :) 
The basic idea is to get some information on degradation - I'll share the (former teslams) display as an attachment (for those wondering, this was one of the first both 75 kWh and facelift cars - as we ordered it as 70 that's the 'upgrade' showing nicely, but also that Tesla at first didn't really software limit them :)
<img width="1537" alt="Schermafbeelding 2019-04-14 om 10 37 16" src="https://user-images.githubusercontent.com/5751088/56090332-5cbac380-5ea1-11e9-86db-25ea24ea51e1.png">

**Comment by lephisto** [comment]
I made an attempt for this, see:

![](https://github.com/lephisto/tesla-apiscraper/raw/master/screenshots/projected_range.png)

**Comment by CoMPaTech** [comment]
Including rated and est that looks very nice @lephisto

**Comment by lephisto** [comment]
It's in the master now if you wanna try.
