### ISSUE TITLE
Sleep code status polling should be more often

### ISSUE THREAD

**Issue by wishbone1138** [lephisto/tesla-apiscraper#37]
Love the sleep back-off algorithm idea, but think that a small tweak might make it better.  

The backoff algorithm should still check for vehicle_state->state every 60 seconds otherwise a wakeup could be missed while waiting for sleep.  Once backoff code triggers (no change between polling?) it should stop running check_states until a multiple of a number of runs is hit that can increase until asleep (or offline) is triggered.

**Comment by lephisto** [comment]
This is the corny thing about the Owner-API. I've been testing this for weeks and months. Every, really every request will keep it from sleeping. That hindsight i finally made me do the Android App.

**Comment by wishbone1138** [comment]
Yeah I just started noticing this as well.  The app idea is great alternative.  I'll play with that.
