### ISSUE TITLE
influx and memory usage

### ISSUE THREAD

**Issue by notnicehat** [lephisto/tesla-apiscraper#42]
First off, this project is cool. Thank you so much. 
Built v4 successfully on an AWS EC2 instance (t3.nano, 512mb) but looking like influx stops responding (but doesn't crash) if it runs low on memory; apiscraper.py does crash when influx stops responding, so the chain effectively stops. I can restart apiscraper, but i'm not sure of a way to check influx if it's working. 

I know that's probably too small of an instance, but I figured I'd start small and work my way up. I also added some swap to the VM in the hope it helps. 
 
What size boxes are you (or others) running on?

**Comment by lephisto** [comment]
You answered most things yourself. 512MB is way too low. It barely runs on a Raspberry Pi w/ 1GB of Ram, which is the absolute minimum. The guys @ influx recommend 8GB of Ram, in the Datacenter I'm fine with 4GB. Remember, it's a inmem index database. Ok, you could try switching from TSM to TSI. But better give it a bit more ram to breathe..

**Comment by notnicehat** [comment]
don't know TSM vs TSI... gonna look that up. I have learned a lot in playing with this project. Thank you for sharing it! 

It seems like it's running okay with 1GB of memory (bumped up to t3.micro) though I am still getting apiscraper timeouts about once a day, but I wrote a hacky every-minute cron job that restarts it and it's been recording well. Thanks again!
