### ISSUE TITLE
Scrape all cars on account

### ISSUE THREAD

**Issue by psarossy** [lephisto/tesla-apiscraper#54]
I see that you can configure the car index on the account, but I can't figure out a way how to scrape all cars on the account without running 2 separate instances. This would still be fine if the config file could be specified on startup but I can't find a way to to that either.

Am I missing something or do I need to maintain 2 copies/instances if I wanna scrape 2 cars?

Thanks in advance!

**Comment by lephisto** [comment]
it should be able to do multiple, but i didn't test it because i can't afford a second tesla :)
