### ISSUE TITLE
Alternative logger: TeslaMate

### ISSUE THREAD

**Issue by adriankumpf** [lephisto/tesla-apiscraper#68]
For those having issues with this apiscraper:

 I built an alternative self-hosted data logger. The installation with docker is quite straightforward and it's actively maintained. Give it a try:

https://github.com/adriankumpf/teslamate

**Comment by bahree** [comment]
Looks really interesting - saw it real quick.

A couple of questions - if you haven't see the install script that [Lunars](https://github.com/Lunars/tesla-apiscraper) build - that can make even the docker installation simpler. Did I understand this correctly- Docker isn't hosting the DB?

Also the manual trigger you have - can that be integrated with something like IFTTT?

**Comment by lephisto** [comment]
No advertising Section here.
