### ISSUE TITLE
Variable query for Car wrong in TeslaMetrics V2

### ISSUE THREAD

**Issue by ServusNL** [lephisto/tesla-apiscraper#69]
The query for getting the car name is wrong in when importing the dashboard TelaMetrics V2. I have copied the query from one of the other templates and now it works.

select distinct(display_name) from (select * from charge_state)

**Comment by lephisto** [comment]
Thanks will put into next rls.

**Comment by nathanpegram** [comment]
I suspect it would be more efficient to use
`show tag values from charge_state with key = "display_name"`
